CREATE DATABASE auth 
  WITH ENCODING='UTF8' 
  LC_COLLATE='C' 
  LC_CTYPE='C' 
  TEMPLATE=template0;

CREATE DATABASE room 
  WITH ENCODING='UTF8' 
  LC_COLLATE='C' 
  LC_CTYPE='C' 
  TEMPLATE=template0;

CREATE DATABASE booking 
  WITH ENCODING='UTF8' 
  LC_COLLATE='C' 
  LC_CTYPE='C' 
  TEMPLATE=template0;