// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/room/v1/room.proto

package roomv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckRoomExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRoomExistsRequest) Reset() {
	*x = CheckRoomExistsRequest{}
	mi := &file_proto_room_v1_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRoomExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRoomExistsRequest) ProtoMessage() {}

func (x *CheckRoomExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRoomExistsRequest.ProtoReflect.Descriptor instead.
func (*CheckRoomExistsRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRoomExistsRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type CheckRoomExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRoomExistsResponse) Reset() {
	*x = CheckRoomExistsResponse{}
	mi := &file_proto_room_v1_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRoomExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRoomExistsResponse) ProtoMessage() {}

func (x *CheckRoomExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRoomExistsResponse.ProtoReflect.Descriptor instead.
func (*CheckRoomExistsResponse) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{1}
}

func (x *CheckRoomExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

var File_proto_room_v1_room_proto protoreflect.FileDescriptor

const file_proto_room_v1_room_proto_rawDesc = "" +
	"\n" +
	"\x18proto/room/v1/room.proto\x12\aroom.v1\"1\n" +
	"\x16CheckRoomExistsRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"1\n" +
	"\x17CheckRoomExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists2c\n" +
	"\vRoomService\x12T\n" +
	"\x0fCheckRoomExists\x12\x1f.room.v1.CheckRoomExistsRequest\x1a .room.v1.CheckRoomExistsResponseBSZQgithub.com/internships-backend/test-backend-mihaillepenkin/pkg/api/room/v1;roomv1b\x06proto3"

var (
	file_proto_room_v1_room_proto_rawDescOnce sync.Once
	file_proto_room_v1_room_proto_rawDescData []byte
)

func file_proto_room_v1_room_proto_rawDescGZIP() []byte {
	file_proto_room_v1_room_proto_rawDescOnce.Do(func() {
		file_proto_room_v1_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_room_v1_room_proto_rawDesc), len(file_proto_room_v1_room_proto_rawDesc)))
	})
	return file_proto_room_v1_room_proto_rawDescData
}

var file_proto_room_v1_room_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_room_v1_room_proto_goTypes = []any{
	(*CheckRoomExistsRequest)(nil),  // 0: room.v1.CheckRoomExistsRequest
	(*CheckRoomExistsResponse)(nil), // 1: room.v1.CheckRoomExistsResponse
}
var file_proto_room_v1_room_proto_depIdxs = []int32{
	0, // 0: room.v1.RoomService.CheckRoomExists:input_type -> room.v1.CheckRoomExistsRequest
	1, // 1: room.v1.RoomService.CheckRoomExists:output_type -> room.v1.CheckRoomExistsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_room_v1_room_proto_init() }
func file_proto_room_v1_room_proto_init() {
	if File_proto_room_v1_room_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_room_v1_room_proto_rawDesc), len(file_proto_room_v1_room_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_room_v1_room_proto_goTypes,
		DependencyIndexes: file_proto_room_v1_room_proto_depIdxs,
		MessageInfos:      file_proto_room_v1_room_proto_msgTypes,
	}.Build()
	File_proto_room_v1_room_proto = out.File
	file_proto_room_v1_room_proto_goTypes = nil
	file_proto_room_v1_room_proto_depIdxs = nil
}
